### ISSUE TITLE
Handle multiple user under same IP

### ISSUE THREAD

**Issue by Ashu-Barnwal** [express-rate-limit/express-rate-limit#337]
### Description

How we can handle multiple users under same IP. As of now limitation on request is as per IP

### Why

Its important since user connected to same wifi network share same IP, due to which if request is exhausted other users are restricted.

### Alternatives

May have unique ID of a user and based on that ID plus IP, user should be restricted

**Comment by nfriedly** [comment]
Yeah, there's two basic ways to handle this.

1) Just set the limit high enough that even multiple users on the same IP can reasonably be accommodated.

2) Use some other form of identification such as User ID or API Key instead of IP address - you can supply a custom `keyGenerator()` function to do this.

You can also do some combination of these, e.g. if users are logged in, then they have their own limit, otherwise use their IP and their limit is shared with everyone else on that IP.

**Comment by Ashu-Barnwal** [comment]
Thank you this was helpful...
