### ISSUE TITLE
Leaky bucket strategy

### ISSUE THREAD

**Issue by Zirafnik** [express-rate-limit/express-rate-limit#359]
### Description

As is, the express-rate-limit uses the following strategy:

Inside the `windowMs` time frame, the app can accept `max` number of requests. After that, further requests are blocked, until the `reset-timer` expires, which equals the `windowMs` time. When the reset-times expires, the `remaining` count is set back to 0 and the client can again burst the `max` requests.

Example:
`windowMs` = 1min
`max` = 10

I can fire 10 request in 1 second. After that I am blocked until the `reset-timer` expires, which equals the `windowMs` (in our case 1 min). So once the 1 min is around, the `remaining` counter is set back to 0 and I can once again fire all 10 requests in 1 sec. 

### Why

What I propose is a leaky bucket strategy, where the `remaining` counter slowly decrements, to allow for further requests, without having to wait for the whole `reset-time` (`windowMs`) time frame.

Additionally, this would prevent burstiness after the `reset-time` expires.

**I propose the Store should slowly decrement the `remaining` count, at a rate: `windowMs`/`max`**  In the above example: 60000ms/10 = 6000ms

This would gradually empty space for new request, while not allowing for bursts with a complete reset.

### Alternatives

.

**Comment by nfriedly** [comment]
That's a good idea! I don't think I want to do it for the default store due to the additional overhead and complexity it adds, but I'd be happy for you to build a new store that implemented your strategy.

We have a guide for creating your own store at https://github.com/express-rate-limit/express-rate-limit/wiki/Creating-Your-Own-Store and then once you have it ready, I'd link to it from the Readme here.

**Comment by Zirafnik** [comment]
Hey, 

I am currently utilizing the Redis store. I was not aware this is handled at the store level? 

I thought the `express-rate-limiter` decided on the strategy (e.g. "Wait for this amount of time, then clear the counter.") and the Stores just exposed the API to do it.

Although it makes sense, for the `reset-timers` to be handled on the Store level.

So to confirm: It is up to the Stores to determine how they will handle resets?

**Comment by nfriedly** [comment]
Yes, it is up to the stores. Most do a per-user window with the count being reset when the user's window expires, but the default one does a global window with all users getting reset at the same time so that it only needs a single timer running. 

It's something I might look into changing eventually, but it'd be a big breaking change, so I'm not sure it will ever happen.
