### ISSUE TITLE
Get Remaining Rate-Limit

### ISSUE THREAD

**Issue by TheCuteFoxxy** [express-rate-limit/express-rate-limit#389]
### Description

The ability to get the remaining rate-limit from the default MemoryStore using the key (i.e IP Address) rather than relying on response headers.

### Why

In the cases of APIs, other parts of the system or users outside the user being ratelimited may need to know how much of a ratelimit is remaining and will not necessarily be able to see the response headers provided.

### Alternatives

Nothing currently, if this already exists somewhere and I did not find it, please let me know and I will close this.

**Comment by nfriedly** [comment]
Yeah, there's a couple ways to accomplish that right now:

* Call increment, save the value, call decrement, subtract one from the value you got from the increment call.

 * Just directly read `store.hits[key]`, BUT this will break in the upcoming 7.0 release, because we re-wrote the MemoryStore.

@gamemaker1 What do you think about adding a new optional method to the store interface to get the hits for a key without incrementing it?

**Comment by gamemaker1** [comment]
We allow incrementing, decrementing and deleting a key already, retrieving a key seems only logical :)

Let's do it, and release it as 6.11?

**Comment by gamemaker1** [comment]
Released v6.11.0 with this feature, although only the memory store supports it atm.

You can call `store.get('1.2.3.4')`, or `limiter.getKey('1.2.3.4')` to use the new function.
