### ISSUE TITLE
Passed options in RateLimitRequestHandler

### ISSUE THREAD

**Issue by Rohit3523** [express-rate-limit/express-rate-limit#407]
Currently their is no way to get the passed options from the RateLimitRequestHandler.

It would be great if the function return an key with name options and have the passed options, so we can use the property to get value for those instead of managing the values at 2 places.

Example:

```
const ratelimiter = ratelimit({
max: 10,
windowMs: 60000
//rest options which are required
});

//we can access the value of Max
console.log(ratelimiter.options.max) //return 10
```

**Comment by nfriedly** [comment]
This is a little bit tricky because express-rate-limit doesn't hang onto the original options passed in, instead it builds and internal configuration object. Additionally, many of the options can be functions that accept the `req` and `res` objects, so they wouldn't be as useful outside the context of a request. 

However, for your example, something like this could work:

```js
const ratelimiterOptions = {
  max: 10,
  windowMs: 60000
  // rest options which are required
}
const ratelimiter = ratelimit(ratelimiterOptions);
ratelimiter.options = ratelimiterOptions;

// we can access the value of Max
console.log(ratelimiter.options.max) //return 10
```
