### ISSUE TITLE
Allow rate limit configuration dynamic based on request comes in (Saas)

### ISSUE THREAD

**Issue by rahulthackkar** [express-rate-limit/express-rate-limit#453]
Hello Team,

I am able to successfully implement rate limit in my standalone node js sample application.
My use case is : One single node application (http api) , connects to different database based on from where request comes in.

Like example1.com/api will served to localhost:3000/example1.com and loads .env specific to example1.com resides in its home directory (say /home/example1.com/.env), which connects to its own database , similarly for other websites, In short my node application is a Software as a service API for hundreds of clients, getting data for each based on request.

I want to implement rate limit in a similar structure, like each client's .env will have limiting configuration(windowMs and limit) as each client have different requirement.

I am trying to setup this rate limit based on this, but I think I can't do it.

Here is a sample code , how I want it.

middleware/tokenRateLimitFactory.js

```js
const rateLimit = require("express-rate-limit");
function tokenRateLimitFactory(req, res, next) {
    const windowMs = process.env.API_RATE_LIMIT_WINDOW ? parseInt(process.env.API_RATE_LIMIT_WINDOW) : 4 * 1000;
    const limit = process.env.API_RATE_LIMIT ? parseInt(process.env.API_RATE_LIMIT) : 2;

    const rateLimitConfig = {
        windowMs: windowMs,
        max: limit,
        message: "Too many requests, please try again later",
        keyGenerator: function (req /*, res*/) {
            return req.headers["authorization"] || req.ip; // Use the Authorization header as the token
        },
        handler: (req, res, next, options) => {
            if (req.rateLimit.used === req.rateLimit.limit + 1) {
                // onLimitReached code here
            }
            res.status(options.statusCode).jsonp({ error: options.message });
        },
    };

    // Create and return the rate limit middleware instance
    const tokenRateLimit = rateLimit(rateLimitConfig);
    tokenRateLimit(req, res, next);
}

module.exports = tokenRateLimitFactory;
```

app.js

```js
const tokenRateLimitFactory = require('./middleware/tokenRateLimitFactory');
app.use(clientResolver); // this loads .env dynamically for each client based on request and further connects to its own database
app.use(tokenRateLimitFactory);
```

But this setup gives an error that

**_ValidationError: express-rate-limit instance should be created at app initialization, not when responding to a request. See https://express-rate-limit.github.io/ERR_ERL_CREATED_IN_REQUEST_HANDLER/ for more information._**

Can you please help me with this?

**Comment by gamemaker1** [comment]
Hi @rahulthackkar,

Could you try removing the last line in the factory function and replace it with a return statement? Like this:

```diff
- tokenRateLimit(req, res, next);
+ return tokenRateLimit
```

That way, you'd return the rate limiter instead of calling it outside a request.

**Comment by rahulthackkar** [comment]
Still same error I am getting.

updated code

`const rateLimit = require("express-rate-limit");

// Middleware factory function that creates a new rate limit middleware instance
function tokenRateLimitFactory(req, res, next) {
    // Get dynamic configuration values from process.env or use default values
    const windowMs = process.env.API_RATE_LIMIT_WINDOW ? parseInt(process.env.API_RATE_LIMIT_WINDOW) : 4 * 1000;
    const limit = process.env.API_RATE_LIMIT ? parseInt(process.env.API_RATE_LIMIT) : 2;

    // Create the rate limit middleware instance with the dynamic configuration
    const rateLimitConfig = {
        legacyHeaders: false,
        windowMs: windowMs,
        max: limit,
        message: "Too many requests, please try again later",
        keyGenerator: function (req /*, res*/) {
            // Extract OAuth2 token from request headers
            return req.headers["authorization"] || req.ip; // Use the Authorization header as the token
        },
        handler: (req, res, next, options) => {
            if (req.rateLimit.used === req.rateLimit.limit + 1) {
                // onLimitReached code here
            }
            res.status(options.statusCode).jsonp({ error: options.message });
        },
    };

    // Create and return the rate limit middleware instance
    const tokenRateLimit = rateLimit(rateLimitConfig);
    return tokenRateLimit(req, res, next);
}

module.exports = tokenRateLimitFactory;
`

**Comment by gamemaker1** [comment]
Don't call the function while returning it:

```
- return tokenRateLimit(req, res, next)
+ return tokenRateLimit
```

**Comment by rahulthackkar** [comment]
Ok, still same error.

ValidationError: express-rate-limit instance should be created at app initialization, not when responding to a request. See https://express-rate-limit.github.io/ERR_ERL_CREATED_IN_REQUEST_HANDLER/ for more information.

**Comment by nfriedly** [comment]
I think I see the issue: The factory is being called on each request, creating a new instance of express-rate-limit. You want the factory to only be called once, at app initialization. Change your app.js like so:

```diff
  const tokenRateLimitFactory = require('./middleware/tokenRateLimitFactory');
  app.use(clientResolver); // this loads .env dynamically for each client based on request and further connects to its own database
- app.use(tokenRateLimitFactory);
+ app.use(tokenRateLimitFactory());
```

...and then change your factory to not expect any arguments, in addition to the change @gamemaker1 suggested:

```diff
  const rateLimit = require("express-rate-limit");
  
  // Middleware factory function that creates a new rate limit middleware instance
- function tokenRateLimitFactory(req, res, next) {
+ function tokenRateLimitFactory() {
      // Get dynamic configuration values from process.env or use default values
      const windowMs = process.env.API_RATE_LIMIT_WINDOW ? parseInt(process.env.API_RATE_LIMIT_WINDOW) : 4 * 1000;
      const limit = process.env.API_RATE_LIMIT ? parseInt(process.env.API_RATE_LIMIT) : 2;
  
      // Create the rate limit middleware instance with the dynamic configuration
      const rateLimitConfig = {
          legacyHeaders: false,
          windowMs: windowMs,
          max: limit,
          message: "Too many requests, please try again later",
          keyGenerator: function (req /*, res*/) {
              // Extract OAuth2 token from request headers
              return req.headers["authorization"] || req.ip; // Use the Authorization header as the token
          },
          handler: (req, res, next, options) => {
              if (req.rateLimit.used === req.rateLimit.limit + 1) {
                  // onLimitReached code here
              }
              res.status(options.statusCode).jsonp({ error: options.message });
          },
      };

    // Create and return the rate limit middleware instance
      const tokenRateLimit = rateLimit(rateLimitConfig);
-     return tokenRateLimit(req, res, next);
+     return tokenRateLimit;
  }
  
  module.exports = tokenRateLimitFactory;
```

**Comment by gamemaker1** [comment]
> The factory is being called on each request, creating a new instance of express-rate-limit. You want the factory to only be called once, at app initialization.

Ahh good catch I didn't see that, thank you!

**Comment by rahulthackkar** [comment]
> I think I see the issue: The factory is being called on each request, creating a new instance of express-rate-limit. You want the factory to only be called once, at app initialization. Change your app.js like so:
> 
> ```diff
>   const tokenRateLimitFactory = require('./middleware/tokenRateLimitFactory');
>   app.use(clientResolver); // this loads .env dynamically for each client based on request and further connects to its own database
> - app.use(tokenRateLimitFactory);
> + app.use(tokenRateLimitFactory());
> ```
> 
> ...and then change your factory to not expect any arguments, in addition to the change @gamemaker1 suggested:
> 
> ```diff
>   const rateLimit = require("express-rate-limit");
>   
>   // Middleware factory function that creates a new rate limit middleware instance
> - function tokenRateLimitFactory(req, res, next) {
> + function tokenRateLimitFactory() {
>       // Get dynamic configuration values from process.env or use default values
>       const windowMs = process.env.API_RATE_LIMIT_WINDOW ? parseInt(process.env.API_RATE_LIMIT_WINDOW) : 4 * 1000;
>       const limit = process.env.API_RATE_LIMIT ? parseInt(process.env.API_RATE_LIMIT) : 2;
>   
>       // Create the rate limit middleware instance with the dynamic configuration
>       const rateLimitConfig = {
>           legacyHeaders: false,
>           windowMs: windowMs,
>           max: limit,
>           message: "Too many requests, please try again later",
>           keyGenerator: function (req /*, res*/) {
>               // Extract OAuth2 token from request headers
>               return req.headers["authorization"] || req.ip; // Use the Authorization header as the token
>           },
>           handler: (req, res, next, options) => {
>               if (req.rateLimit.used === req.rateLimit.limit + 1) {
>                   // onLimitReached code here
>               }
>               res.status(options.statusCode).jsonp({ error: options.message });
>           },
>       };
> 
>     // Create and return the rate limit middleware instance
>       const tokenRateLimit = rateLimit(rateLimitConfig);
> -     return tokenRateLimit(req, res, next);
> +     return tokenRateLimit;
>   }
>   
>   module.exports = tokenRateLimitFactory;
> ```

Thanks for your answer,

**But this does solves this error, but not my concern, let me explain again.**

On each request , I need to identify my client ( my node app is : Multi Tenant Saas GraphQL API) , for that I registered one middleware named clientResolver.

Role of clientResolver is to load .env (/home/domain1.com/.env, /home/domain2.com/.env) for that specific client, and this dynamic .env configuration , I am using for connecting to respective client's database.
Similarly I will have different rate limit configuration for each client , which I need to specify in that particular client's .env file

The approach you suggested doesn't load rate limit module with support of this (Setting configuration on demand(on request)), So here I am not getting anything in process.env.API_RATE_LIMIT_WINDOW OR process.env.API_RATE_LIMIT, because this middle ware is registered on app load time , and these env variables are yet to define.

I think you got, what I want is.

I have Saas structured application, I can not keep same rate limit for everyone.
Hope this information helps.

**Comment by rahulthackkar** [comment]
In short, I want dynamic limit configuration (windowMs and limit for now) 
, which I will decide (based on loaded .env of respective client), after request comes into my app.

So kind of a route middleware you can consider.

**Comment by gamemaker1** [comment]
Dynamically loading the `limit` is supported, but not `windowMs`.

**Comment by rahulthackkar** [comment]
> Dynamically loading the `limit` is supported, but not `windowMs`.

How I can do this?

**Comment by gamemaker1** [comment]
Here is an example:

```ts
const limiter = rateLimit({
	// ...
	limit: async (req, res) => {
		if (/*something*/) return 10
		else return 5
	},
})
```

Please see https://express-rate-limit.mintlify.app/reference/configuration#limit for more info.

**Comment by nfriedly** [comment]
Does `process.env.API_RATE_LIMIT_WINDOW` and `process.env.API_RATE_LIMIT` change for each request? That's very unconventional.

I was thinking you had separate instances of your node.js app for each different env, you could then use something like nginx to send requests to different instances based on the URL.

Failing that, you could create all of your instances of express-rate-limit at the start like so:

```
app.use('/example1.com', rateLimit({ /* settings for example1.com */ })
app.use('/example2.com', rateLimit({ /* settings for example2.com */ })
app.use('/example3.com', rateLimit({ /* settings for example3.com */ })
```

You'd have to load all your settings at app initialization, not when a request comes in, but it would solve your issue. You'd just have to restart the server if you wanted to add a new website.

**Comment by gamemaker1** [comment]
Ah I see @nfriedly beat me to it :D

**Comment by rahulthackkar** [comment]
> Does `process.env.API_RATE_LIMIT_WINDOW` and `process.env.API_RATE_LIMIT` change for each request?

Yes it is, and I can not load all env at once while app loads, as it will totally change my  client onboarding process, 
I want it totally dynamic based on request only.

And I want to know why it is unconventional ? as I am doing database connection in a same way, then will it also an unconventional way?

What I am doing is, only running one app instance , loading dynamic configuration based on request (by identifying client), and doing connection based on that dynamically loaded configuration.

My typical clientResolverMiddleware looks like below

`const dotenv = require("dotenv");

// helpers

// Db connection class
const MySqlConnection = require("../config/mysql");
const objMySqlConnection = new MySqlConnection();

module.exports = async (req, res, next) => {
  const hostname = req.hostname;

  const homeDirPath = "/home/" + hostname;

  let envPath = homeDirPath + "/localconfig/.env";

  //Read the env file
  dotenv.config({ path: envPath });

  //Create the db connection and set it as a global variable
  DB_CONNECTION = await objMySqlConnection.connectdb();

  // Further I am using this DB_CONNECTION in my models or querybuilder
  next();
};
`

Suggest me If I am doing it in a wrong way , Your inputs are appreciated.
Thanks

**Comment by nfriedly** [comment]
> And I want to know why it is unconventional ? as I am doing database connection in a same way, then will it also an unconventional way?

I believe that most code written to check environment properties assumes they will not change while the process is running. The sort of configuration you're doing would normally come from somewhere else.

Regardless, there's two problems:
1. creating a new instance of express-rate-limit for each request resets the hit count to 0 for each request. So it will never block someone for making too many requests.
2. express-rate-limit does not support dynamic `windowMs` values, because a number of the stores have optimizations that depend on having a fixed `windowMs`.

If you could use the same `windowMs` for each of the 500 sites, then it would be easy and only need a single instance of express-rate-limit.

Alternatively, you can create multiple instances, even 500 instances. This is essentially what your original code did, except it created a new instance for each *request* rather than each *website*. The validation error that got logged was meant to catch exactly that mistake, and it worked correctly here.

However, there is a way to make the instance at runtime rather than creation time: you just need to save and re-use it for each subsequent request for that website. The validation error would still get logged, but you could disable it if you ensure that you're only creating one instance of express-rate-limit per website.

Something like this:

```js

const limiterByHostname = {}
app.use((req, res, next) => {
  if (!limiterByHostname[req.hostname]) {
      const windowMs = process.env.API_RATE_LIMIT_WINDOW ? parseInt(process.env.API_RATE_LIMIT_WINDOW) : 4 * 1000;
      const limit = process.env.API_RATE_LIMIT ? parseInt(process.env.API_RATE_LIMIT) : 2;
  
      // Create the rate limit middleware instance with the dynamic configuration
      const rateLimitConfig = {
          validate: { creationStack: false },
          legacyHeaders: false,
          windowMs: windowMs,
          max: limit,
          message: "Too many requests, please try again later",
          keyGenerator: function (req /*, res*/) {
              // Extract OAuth2 token from request headers
              return req.headers["authorization"] || req.ip; // Use the Authorization header as the token
          },
          handler: (req, res, next, options) => {
              if (req.rateLimit.used === req.rateLimit.limit + 1) {
                  // onLimitReached code here
              }
              res.status(options.statusCode).jsonp({ error: options.message });
          },
      };
      limiterByHostname[req.hostname] = rateLimit(rateLimitConfig);
  } 
  const limiter = limiterByHostname[req.hostname];
  limiter(req, res, next);
}
```

Because it's saving the instance in `limiterByHostname` and reusing it on subsequent requests for that site, it should work for you.

---

As an aside, I feel like there's probably also some latent issues in your database connection code. Off the top of my head,
* If two requests come in parallel, one may end up using the other one's db connection
    * You could address this by associating the connection with the request, rather than a global vairable, e.g. 
        ```diff
        - DB_CONNECTION = await objMySqlConnection.connectdb();
        + req.dbConnection = await objMySqlConnection.connectdb();
       ```
       And then update anyplace that uses `DB_CONNECTION` and change it to use `req.dbConnection`.
* If you're opening a new connection for every request, but never closing it, you may end up hitting some maximum number of connections eventually.
    * You could address this by closing the connection after the response is sent:
    ```js
    res.on('close', () => {
        req.dbConnection.close(); // or whatever code will close the db connection
   ```
   Note that it uses `res` on the first line and `req` on the second!

It sounds like you're trying to follow best practices, but using ones that were intended for when the codebase is serving a single site and may cause trouble when serving more than one. Serving multiple sites from a single instance is just trickier than serving a single one, and can have a lot of gotchas like these.

**Comment by nfriedly** [comment]
Oh, and just an FYI, in github comments, a single backtick (\`) is for an inline code sample `like this` , but when you have a multiline code sample you want to use 3 backticks (\```)before and after it

```
like
this
```

You can also put the file extension after the top three backticks for syntax hilighting, e.g. \```js

I edited some of your earlier comments, so you can hit edit on those and see the changes I made.

See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax for more info.

**Comment by rahulthackkar** [comment]
Oh, I see, you helped me a lot Nathan,
I will try with your provided code sample.
Also I had doubt about this global connection variable, but you cleared it.

It really means a lot.
Thanks

**Comment by rahulthackkar** [comment]
> It sounds like you're trying to follow best practices, but using ones that were intended for when the codebase is serving a single site and may cause trouble when serving more than one. Serving multiple sites from a single instance is just trickier than serving a single one, and can have a lot of gotchas like these.

Thanks for your help, one more question, not related to this package

Should I follow below architecture for multiple websites but single node app?

* Single code base 
* Symbolic link of code base to each client along with their own local-configs and code (they can override if needed).
* My node app will register all available clients using app.use(vhost)


```javascript
........
.......
// Hosts
const vhost = require('vhost');
const hosts = require('./hosts');
........
........
each(hosts, (customers, key) => {
    if (customers.constructor === Object && !isEmpty(customers)) {
        each(customers, (path, domain) => {
            // register customer's vhost
            app.use(vhost(`${key}.${domain}`, require(join(path, 'app')).app));

            // SSL certificate tls context
            const sslCertiPath = join(path, 'local/ssl');
            if (
                existsSync(join(sslCertiPath, 'server.key')) && 
                existsSync(join(sslCertiPath, 'server.crt')) && 
                existsSync(join(sslCertiPath, 'server.cabundle'))
            ) {
                defaultSSLConfig = {
                    key: readFileSync(join(sslCertiPath, 'server.key')).toString(),
                    cert: readFileSync(join(sslCertiPath, 'server.crt')).toString(),
                    ca: [readFileSync(join(sslCertiPath, 'server.cabundle')).toString()]
                }

                tlsContext[domain] = createSecureContext(defaultSSLConfig).context
            }
        });
    }
});
```

hosts.js
```javascript
module.exports = {
    'api': {
        'www.domain1.com': '/home/user1/api', // will be symbolic link to my main app
        'www.domain2.com': '/home/user2/api', // will be symbolic link to my main app
    }
}
```
* So each client will have their own app (exported), I will require that in my main app for each client registered, and run my single app, so it will do everything on app load , for each client I will have connection pool, ratelimiter instances, or any other things which are needed for client specific.

Thanks

**Comment by rahulthackkar** [comment]
> Something like this:
> 
> ```js
> const limiterByHostname = {}
> app.use((req, res, next) => {
>   if (!limiterByHostname[req.hostname]) {
>       const windowMs = process.env.API_RATE_LIMIT_WINDOW ? parseInt(process.env.API_RATE_LIMIT_WINDOW) : 4 * 1000;
>       const limit = process.env.API_RATE_LIMIT ? parseInt(process.env.API_RATE_LIMIT) : 2;
>   
>       // Create the rate limit middleware instance with the dynamic configuration
>       const rateLimitConfig = {
>           validate: { creationStack: false },
>           legacyHeaders: false,
>           windowMs: windowMs,
>           max: limit,
>           message: "Too many requests, please try again later",
>           keyGenerator: function (req /*, res*/) {
>               // Extract OAuth2 token from request headers
>               return req.headers["authorization"] || req.ip; // Use the Authorization header as the token
>           },
>           handler: (req, res, next, options) => {
>               if (req.rateLimit.used === req.rateLimit.limit + 1) {
>                   // onLimitReached code here
>               }
>               res.status(options.statusCode).jsonp({ error: options.message });
>           },
>       };
>       limiterByHostname[req.hostname] = rateLimit(rateLimitConfig);
>   } 
>   const limiter = limiterByHostname[req.hostname];
>   limiter(req, res, next);
> }
> ```
> 
> Because it's saving the instance in `limiterByHostname` and reusing it on subsequent requests for that site, it should work for you.

This worked for me! 
Thanks

**Comment by nfriedly** [comment]
> * Single code base
> ...
> * So each client will have their own app (exported), I will require that in my main app for each client registered, and run my single app, so it will do everything on app load , for each client I will have connection pool, ratelimiter instances, or any other things which are needed for client specific.

You can certainly do that. I'd recommend looking ways that things can be shared between all sites rather than duplicating them for each site.

The other concern I'd have is around using only a single process to serve everything. Both because most servers have multiple CPU cores (so you're wasting most of them by only using a single process), and because an error in one site can potentially take them all down. 

You can use the [cluster](https://nodejs.org/api/cluster.html) module to have one parent and multiple child processes, where the child processes split up the work, and the parent acts as a "watchdog", automatically creating new child processes any time one crashes. 

You can see a fairly basic example of this in the cluster-memory-store I made for express-rate-limit: https://github.com/express-rate-limit/cluster-memory-store/blob/main/example/server.js 

However, you have to be more careful about application state (like hit counts for the rate limiter). You already have a mySQL database, so you're probably in good shape there, but little things can occasionally surprise you. For express-rate-limit you could use either the aforementioned [cluster-memory-store](https://www.npmjs.com/package/@express-rate-limit/cluster-memory-store), or mySQL via TypeORM (although I'm not sure how easy that is to use without typescript), or another store with, e.g. a memcached server.

**Comment by WesCossick** [comment]
I just came across this discussion, as we're in a similar boat. We use `express-rate-limit` to rate limit an API with many endpoints. Those endpoints each have their own settings for the `limit` and the `windowMs`, with more sensitive endpoints using more restrictive settings (e.g., 5 requests per hour vs. 25 requests per minute).

The endpoints are file system driven, so there's not an explicit Express route for each one. We do this because there can be thousands of endpoints.

The rate limiting we enforce is also designed to be endpoint-specific. So a user could be blocked from using a specific endpoint with a restrictive rate limit, but still able to use a non-sensitive endpoint with a more-permissive rate limit.

After upgrading `express-rate-limit`, we started encountering these `ERR_ERL_CREATED_IN_REQUEST_HANDLER` errors. But there doesn't seem to be a good way to address this situation without defining the rate limiting instance per-request.

For example, here's what the endpoint-specific rate limiting looks like:

```ts
app.use((req, res, next) => {
	const limiter = rateLimit({
		store: new redisStore({
			expiry: req.endpointSpec.protection.block.window,
			client: redisClient,
			prefix: `rl:${req.action} ${req.uri}:block`,
		}),
		windowMs: req.endpointSpec.protection.block.window,
		limit: req.endpointSpec.protection.block.afterRequests,
		handler: (req, res) => {
			// Responds with an error here
		},
	});
	
	limiter(req, res, next);
});
```

In the code above, you can see that we're using dynamic per-request values in `limit` and `windowMs`, along with the Redis store's `expiry` and `prefix`. I see that we can turn `limit` into a function, but not any of the other three keys. Are there any plans to update `express-rate-limit` to support this kind of use case? If not, is it problematic to disable the check via `creationStack: false`?

**Comment by nfriedly** [comment]
@WesCossick yeah, I think for your case, it's safe to go ahead and disable that check. 

I think I need to narrow its scope a little bit, to only apply when the memory store is in use.

**Comment by nfriedly** [comment]
@WesCossick One thing I wanted to mention is that the redis store does a bit of initialization logic at the first request, uploading a lua script to the server. It's not the end of the world to do this on each request, but it is a bit of extra overhead to be aware of. You could bypass this by caching the limiter and re-using it on subsequent requests that would otherwise create an identical limiter.

Another thing that comes to mind after a second look is that the prefix feels wrong. Including the action is a little weird leading to separate counters for GET/POST/etc., but I suppose it could make sense in some scenarios. However, I'm more concerned that `req.uri` might include the querystring, and therefore a malicious actor could just add a counter and get unlimited requests.

**Comment by WesCossick** [comment]
That's really good to know about the extra initialization logic. We'll look into caching the limiter and how much of a performance gain that would offer. For now, it's not causing any noticeable performance issues.

> Including the action is a little weird leading to separate counters for GET/POST/etc.

That's actually the design we're after. I didn't mention it, but we have a global rate limiter that is not dependent on the endpoint, which applies to all incoming API calls; this is just an extra level of protection for more sensitive endpoints to block individual ones from being abused.

> I'm more concerned that `req.uri` might include the querystring

I also didn't go into much detail with `req.uri`, but that's a custom key our own code sets. It's the path portion of the endpoint, so for a hypothetical `GET /users` endpoint the `/users` part would be stored in the `uri` key. The query string wouldn't be stored in that key.
