### ISSUE TITLE
Fix changelog

### ISSUE THREAD

**Issue by ehmicky** [express-rate-limit/express-rate-limit#464]
### Description

The [release notes](https://github.com/express-rate-limit/express-rate-limit/releases/tag/v7.3.1) are pointing to the changelog file, but the file location is incorrect. It points to a root `changelog.md` instead of https://github.com/express-rate-limit/express-rate-limit/blob/main/docs/reference/changelog.mdx

Also, the [changelog on the website](https://express-rate-limit.mintlify.app/reference/changelog) is currently at `7.2.0`, i.e. missing the last two releases and not in sync with https://github.com/express-rate-limit/express-rate-limit/blob/main/docs/reference/changelog.mdx

### Library version

7.3.1

### Node version

22.3.0

### Module system

ESM

**Comment by gamemaker1** [comment]
Ah thanks for pointing that out, I'll fix the release note link right away.

As for the website not being updated, it's because the Mintlify deploy workflow isn't working anymore. We're working on finding a solution to that problem.

@nfriedly maybe we should add a note or something to the readme pointing out that the website is out of date? And if the issue doesn't get fixed soon, try to build and host the documentation ourself at express-rate-limit.github.io?

**Comment by nfriedly** [comment]
This is now fixed. Apparently Mintlify had changed their system to only allow one primary editor on free projects, but it broke on our account because we already had multiple. They've fixed it now, and the docs should be up-to-date once again.

**Comment by ehmicky** [comment]
Thanks!
